In [62]:
import pandas as pd 

df = pd.read_csv('resultado_desarmes.csv')
df.head()

,Jogadora,Time,POS,Minutos,Desarmes(2/3),Desarmes(3/3),Desarmes Total,Desarmes Ganhos,SCA DEF,GCA DEF
0,Ali Riley,Angel City,DF,260,1,0,2,2,0,0
1,Alyssa Thompson,Angel City,FW,2144,15,8,45,33,1,0
2,Amandine Henry,Angel City,MF,263,3,1,7,6,1,0
3,Angelina Anderson,Angel City,GK,270,0,0,0,0,0,0
4,Christen Press,Angel City,FW,203,2,2,5,4,0,0

In [63]:
df = df[df['Minutos'] >= 900]

# Calcular a eficiência (evitando divisão por zero)
df['eficiencia'] = df['Desarmes Ganhos'] / df['Desarmes Total']
df['eficiencia'] = df['eficiencia'].fillna(0)  # Substituir valores NaN por 0 caso Desarmes Total seja zero

# Calcular a nova métrica
df['IDO'] = (
    (df['SCA DEF'] + df['GCA DEF'] + df['Desarmes(3/3)'])
    * df['eficiencia']
)

# Ordenar pela nova métrica em ordem decrescente
df = df.sort_values(by='IDO', ascending=False)
df.index = range(1, len(df) + 1)
df.head(10)

,Jogadora,Time,POS,Minutos,Desarmes(2/3),Desarmes(3/3),Desarmes Total,Desarmes Ganhos,SCA DEF,GCA DEF,eficiencia,IDO
1,Emma Sears,Louisville,"FW,MF",1482,14,14,40,26,7,1,0.650000,14.300000
2,Racheal Kundananji,Bay FC,"FW,MF",1824,21,18,52,31,5,0,0.596154,13.711538
3,Rose Lavelle,Gotham,"MF,FW",1413,11,15,32,23,2,0,0.718750,12.218750
4,Yazmeen Ryan,Gotham,"MF,FW",1939,19,13,46,33,4,0,0.717391,12.195652
5,Lo'eau LaBonta,Current,MF,1920,19,9,44,36,5,0,0.818182,11.454545
6,Haley Hanson,Pride,MF,1698,20,14,46,31,2,0,0.673913,10.782609
7,Jaedyn Shaw,Wave,"MF,FW",1248,15,10,32,24,4,0,0.750000,10.500000
8,Tess Boade,Bay FC,"MF,FW",2044,20,10,45,31,4,1,0.688889,10.333333
9,Crystal Dunn,Gotham,"FW,MF",1056,15,14,45,31,1,0,0.688889,10.333333
10,Temwa Chawinga,Current,FW,2142,15,15,49,28,3,0,0.571429,10.285714

In [65]:
df = df.drop('Desarmes(2/3)', axis=1)

In [67]:
df.to_csv("IDO.csv")